### ISSUE TITLE
Build error. Property 'enabled' cannot be accessed on 'Flag?' because it is potentially null

### ISSUE THREAD

**Issue by AndrewBotalov80** [Flagsmith/flagsmith-flutter-client#22]
flutter/.pub-cache/hosted/pub.dartlang.org/flagsmith_core-2.1.0+1/lib/src/storage_provider.dart:141:68: Error: Property 'enabled' cannot be accessed on 'Flag?' because it is potentially null.
 - 'Flag' is from 'package:flagsmith_core/src/model/flag.dart' ('/usr/local/Caskroom/flutter/1.22.2/flutter/.pub-cache/hosted/pub.dartlang.org/flagsmith_core-2.1.0+1/lib/src/model/flag.dart').
Try accessing using ?. instead.
    log('_updateSubject ${item.key} -> ${_streams[item.key]?.value.enabled} f: ${item.enabled}');

../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flagsmith-2.0.1+2/lib/src/store/storage_provider.dart:131:68: Error: Property 'enabled' cannot be accessed on 'Flag?' because it is potentially null.
 - 'Flag' is from 'package:flagsmith/src/model/flag.dart' ('../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flagsmith-2.0.1+2/lib/src/model/flag.dart').
Try accessing using ?. instead.
    log('_updateSubject ${item.key} -> ${_streams[item.key]?.value.enabled} f: ${item.enabled}');

FAILURE: Build failed with an exception.

Flutter: 2.5.3
environment:
  sdk: ">=2.3.0 <3.0.0"

**Comment by AndrewBotalov80** [comment]
Looks more like an error after migrating the project to flutter 2 and still without null safety :)

**Comment by brax10ward** [comment]
@AndrewBotalov80 Were you able to resolve the problem?
