### ISSUE TITLE
404 on flags call in v3

### ISSUE THREAD

**Issue by momrak** [Flagsmith/flagsmith-flutter-client#30]
After upgrading to v3 we get 404 using the new default edge URL. Is this a bug, or is there something that we need to fix in order to use the new version?

<img width="559" alt="image" src="https://user-images.githubusercontent.com/6552049/173043987-6974d58a-6c63-416d-8ce9-18f3e90a592e.png">

**Comment by dabeeeenster** [comment]
Hi there - yes you will need to upgrade to our Edge API - please contact us via in-app chat and we can migrate you!
