### ISSUE TITLE
CORS errorr on /traits/bulk

### ISSUE THREAD

**Issue by momrak** [Flagsmith/flagsmith-flutter-client#31]
I get `method disallowed by preflight response` on `/traits/bulk` call. Is this something with the new edge API, or something we need to fix? 

<img width="1709" alt="image" src="https://user-images.githubusercontent.com/6552049/173047903-399dc9ae-faf7-4c0e-92fc-130cc9aeef7b.png">

**Comment by dabeeeenster** [comment]
Hi @momrak - yes - this has come out of the Edge API - this should not be present in the Flutter SDK but it must have slipped through. Apologies for this. We'll work to take it out of the Flutter SDK but for now you can consider that feature deprecated.

**Comment by dabeeeenster** [comment]
You can achieve a bulk trait update with something like this:

```
## Get Flags With Identifier and Traits
curl -X "POST" "https://edge.api.flagsmith.com/api/v1/identities/?identifier=winning2" \
     -H 'X-Environment-Key: <key>' \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "traits": [
    {
      "trait_value": 1000,
      "trait_key": "gagan_1"
    },
    {
      "trait_value": true,
      "trait_key": "my_other_key"
    },
    {
      "trait_value": "ben2",
      "trait_key": "my_other_key_string"
    }
  ],
  "identifier": "winning2"
}'
```

**Comment by momrak** [comment]
I see. I am not manually calling this, but I guess it is done when the updateTraits is called here?
```
      await _client.initialize();
      await _client.updateTraits(value: traits);
      await _client.getFeatureFlags(user: Identity(identifier: id), reload: true);
```

Also, all the flags calls you see above, I noticed on your webpage it says
> How does it work?
Every time a flag is evaluated within the SDK (generally a call to a method like flagsmith.hasFeature("myCoolFeature")), the SDK keeps a track of the flag name along with an evaluation count.
Every n seconds (currently set to 10 seconds in the JS SDK) the SDK sends a message to the Flagsmith API with the list of flags that have been evaluated and their count. If no flags have been evaluated in that time window, no message is sent.

However all these calls are empty and no flags have been evaluated, so I would think now message should be sent. Is this a bug?

**Comment by momrak** [comment]
`0` is also logged to the console for each of these requests, except when there actually was an evaluation, then it logged 1, so I guess it logs the number of evaluated flags or so, which is a bit annoying to have show up in the console

**Comment by dabeeeenster** [comment]
Hi @momrak  - we're looking into this and will have an update early next week - apologies for this miss.

**Comment by momrak** [comment]
Cool, thanks for your help :)

**Comment by dabeeeenster** [comment]
Fixed in current version
