### ISSUE TITLE
Analytics sends request even if no flags are evaluated

### ISSUE THREAD

**Issue by momrak** [Flagsmith/flagsmith-flutter-client#35]
Version: 3.0.1

Reading the docs when it comes to the analytics/flag call I would expect it to be sent only when a flag has actually been avaluated. Now it will send one every 10th second. 

Also it logs 0, which I guess is the number of evaluated flags, to the console each time it send a request. If a flag has actually been evaluated it sends 1, etc.

> How does it work?
Every time a flag is evaluated within the SDK (generally a call to a method like flagsmith.hasFeature("myCoolFeature")), the SDK keeps a track of the flag name along with an evaluation count.
Every n seconds (currently set to 10 seconds in the JS SDK) the SDK sends a message to the Flagsmith API with the list of flags that have been evaluated and their count. If no flags have been evaluated in that time window, no message is sent.
<img width="703" alt="image" src="https://user-images.githubusercontent.com/6552049/174297075-1fe6eac5-e6d9-4caa-bfc1-2250a777a414.png">

**Comment by dabeeeenster** [comment]
- [ ] The SDK should only POST evaluation events if any have been generated since the last `syncAnalyticsData`
- [ ] The logging should be removed when `syncAnalyticsData` event runs without error

**Comment by dabeeeenster** [comment]
Merged!
