### ISSUE TITLE
`Bad state: Future already completed` on `client.getFeatureFlags` call

### ISSUE THREAD

**Issue by momrak** [Flagsmith/flagsmith-flutter-client#36]
This line seems to cause an error at our side. (see attached image)
`await _client.getFeatureFlags(user: Identity(identifier: id), reload: true);`
When I remove the line there is no error. Is this something you have seen before, or have any idea what it could be?

This is how we init the client
```
    try {
      await _client.initialize();
      await _client.updateTraits(value: traits);
      await _client.getFeatureFlags(user: Identity(identifier: id), reload: true);
      _ready = true;
    } catch (e, s) {
      _logger.warn('failed to init feature flag client', stacktrace: s, payload: {'error': e});
    }
```

<img width="706" alt="image" src="https://user-images.githubusercontent.com/6552049/174302612-07667b4a-fb42-482d-b8d6-0248101e575b.png">

**Comment by dabeeeenster** [comment]
Thanks @momrak - we're looking into this

**Comment by jackforesightmobile** [comment]
Hi @momrak, I've investigated this and I don't think the issue is on our end. It seems to be an issue with the Dio package that we have as a dependency.

https://github.com/flutterchina/dio/issues/1480
https://github.com/flutterchina/dio/issues/1497
