### ISSUE TITLE
Problem with using shared preference storage

### ISSUE THREAD

**Issue by konoshenko** [Flagsmith/flagsmith-flutter-client#39]
Flutter: 
<img width="732" alt="Screenshot 2022-07-06 at 14 36 51" src="https://user-images.githubusercontent.com/102408516/177541530-357dc639-0171-4588-aba2-72e4d2964c96.png">

How use:
<img width="732" alt="Screenshot 2022-07-06 at 14 34 47" src="https://user-images.githubusercontent.com/102408516/177541276-487be23c-f320-44f6-9cf0-33566772ffd1.png">
Pubspec:
<img width="732" alt="Screenshot 2022-07-06 at 14 35 21" src="https://user-images.githubusercontent.com/102408516/177541313-c8f5501c-886a-420d-a5da-016b6e5df625.png">

**Comment by konoshenko** [comment]
FYI @jackforesightmobile

**Comment by konoshenko** [comment]
Problem with imports. In FlagsmithClient you are import CoreStorage from core_flagsmith but in FlagsmithSharedPreferencesStore import CoreStorage from core_flutter_flagsmith

**Comment by jackforesightmobile** [comment]
@konoshenko you can now use the flagsmith_storage package to resolve this issue: https://pub.dev/packages/flagsmith_storage
