### ISSUE TITLE
Allow to pass a mock dio instance into FlagsmithClient

### ISSUE THREAD

**Issue by jeduden** [Flagsmith/flagsmith-flutter-client#4]
In order to execute integration test without depending on the network with the `FlagsmithClient`, it would be great if the application could inject a mock `dio` instance into the `FlagsmithClient`. This would enable the use of packages like [http_mock_adapter](https://pub.dev/packages/http_mock_adapter) with the client.

Would you consider merging a PR with this functionality ?

**Comment by dabeeeenster** [comment]
yes for sure!
