### ISSUE TITLE
[Documentation] hasFeatureFlag is not properly documented

### ISSUE THREAD

**Issue by daniloapr** [Flagsmith/flagsmith-flutter-client#44]
The method `hasFeatureFlag` is saying in the docs:
```
/// Check if Feature flag exist and is enabled in cache
```
However, it should be only:
```
/// Check if Feature flag exists
```

To check if the flag exists AND is enabled, there is the method `isFeatureFlagEnabled`.

It is also wrong in the official [website](https://docs.flagsmith.com/clients/flutter).

**Comment by dabeeeenster** [comment]
Thanks! This is fixed in https://github.com/Flagsmith/flagsmith-docs/commit/1818f48f43e71d9a2cf7ecfb1f5906cb6606d8c8
