### ISSUE TITLE
Dependency dio produces errors dio version >= 4.0.4 fails with "Future already completed"

### ISSUE THREAD

**Issue by jdde** [Flagsmith/flagsmith-flutter-client#45]
Hi guys, I just tried to see if the new dio v4.0.6 resolved the issue mentioned in your documentation https://docs.flagsmith.com/clients/flutter#known-issues
"If using the package Dio, you may encounter an error saying Bad state: Future already completed. There is a bug in the Dio package, introduced in 4.0.5 (and as of writing this on 12/09/2022, is unresolved). To resolve, you'll need to pin your Dio version in pubspec.yaml to 4.0.4 or earlier."

Unfortunately this is **not** the case.

I'll attach my test results as screenshots.
I reproduced it easily, by just locking the dio version in the sdk itself & in the example application.
Then start it for web - see if the error occurs.

Here you can see the result with different version - 4.0.4, 4.0.5, 4.0.6

Web state with dio 4.0.4
<img width="3111" alt="dio_4_0_4" src="https://user-images.githubusercontent.com/10098106/204753166-8b37fd7c-78c4-4f29-9d2b-993fcd17ca7e.png">

Web state with dio 4.0.5
<img width="2523" alt="dio_4_0_5" src="https://user-images.githubusercontent.com/10098106/204753197-561c9e6b-37ea-4464-b00c-ca0c62ecd353.png">

Web state with upgrading dio to 4.0.6
<img width="3107" alt="dio_4_0_6" src="https://user-images.githubusercontent.com/10098106/204753222-0d437ff6-abb6-4a6f-8e97-32932e02b7b9.png">

**Comment by dabeeeenster** [comment]
@matthewelwell can we close this issue on account of https://github.com/Flagsmith/flagsmith-flutter-client/pull/48 ?
